[app]
identifier = "com.example.hello"
display_name = "Hello"
slug = "hello"
version = "0.1.0"

[linux]
binaries = { x86_64 = "zig-out/bin/hello" }

[macos]
binaries = { aarch64 = "zig-out/bin/hello", x86_64 = "zig-out/bin/hello" }

[windows]
binaries = { x86_64 = "zig-out/bin/hello.exe" }

[gui]
initial_width = 400
initial_height = 400
max_width = 400
max_height = 400
min_width = 200
min_height = 200

[fonts]
families = [{ nerdfont = "BigBlueTerminal" }]

[environment]
variables = { HELLO_FROM = "trolley" }

[ghostty]
font-size = 12
title = "🚃 Trolley Express — Hello World Terminal 🌍"
